### ISSUE TITLE
Printing is slow

### ISSUE THREAD

**Issue by bluebear94** [ab5tract/Terminal-Print#2]
None of the examples have any sleep commands inside printing loops, yet outputting a single character to a screen takes about ~~50~~ 20ms.

If improving the performance isn't possible, then you should at least show users how to work around this problem.

**Comment by bluebear94** [comment]
Any reason we have to use `tput cup <row> <col>` instead of printing the appropriate ANSI escape codes?

**Comment by bluebear94** [comment]
Regex substitution of output of `tput cup 13 13` takes about 2 - 5 ms on average.

Using `return "\e[{$y+1};{$x+1}H";` takes about 1 ms on average.

Obviously hardcoding the escape string might not be ideal.

**Comment by bluebear94** [comment]
Also, in alphabetics.pm6, you might want to change the sigil on `$alphabet` to `@alphabet`.

**Comment by ab5tract** [comment]
ANSI escape codes are not guaranteed to work everywhere. tput is used to
guarantee that we are getting the precise codes that the current terminal
support.

IIRC correctly, it was at one point significantly faster to shell out to
tput directly rather than use the sort of "live" regex that I generate in
Terminal::Print::Commands. But I do not want to switch to ANSI only codes.

Regarding the sigil, that's a taste thing. I consider a range to be a
single object. If you look at the example, there is an @alphabets commented
out that holds a list of ranges. $alphabet then refers to one of those
ranges.

**Comment by ab5tract** [comment]
To be clear, you can try replacing the regex sub with just a qq:x{ tput
{$y+1} {$x+1} } if you are interested in testing the speed difference.

**Comment by bluebear94** [comment]
I asked you to change the sigil to `@` since it makes the alphabetics code run faster.

**Comment by bluebear94** [comment]
Doing this reduces the performance even more (60 - 70 ms).

I'd suggest building a string made for sprintf, and/or allowing the program to assume support for ANSI codes given a certain flag.

**Comment by ab5tract** [comment]
Feel free to submit PRs for these.

**Comment by ab5tract** [comment]
And we can also be happy that regexes are faster than shelling out these
days :)

On Sun, Nov 1, 2015 at 6:27 PM, John Haltiwanger <john.haltiwanger@gmail.com

**Comment by ab5tract** [comment]
Please see commit 715fd07d0bf13d1808bb7d6d12cbd9956d3872fa and let me know if this addresses things for you.

**Comment by bluebear94** [comment]
There are still performance issues, especially noticeable in the async example. For instance, every now and then printing will slow down.

**Comment by bluebear94** [comment]
```
submethod BUILD( :$!max-columns, :$!max-rows, :$!move-cursor-profile = 'ansi' ) {
    @!grid-indices = (^$!max-columns X ^$!max-rows)>>.Array;
    for @!grid-indices -> [$x,$y] {
        @!grid[$x;$y] = Str.new(:value(" "));
    }
    $!character-supply = Supply.new;
    $!control-supply = Supply.new;

    &!move-cursor-template = %T::human-commands<move-cursor>{ $!move-cursor-profile };
}
```
Also, any reason why you use `Str.new(:value(" "))` instead of just plain `" "`?

**Comment by ab5tract** [comment]
Yes, the async example does have this slow down. I wonder if it would be a benefit here to establish a "framerate" that synchronizes printing. So print-cell would really only concatenate onto a "frame string" which would then be printed out N times a second.

Not sure why I used the Str constructor form there. If it works when changing it, feel free to remove.

We should also test performance with a non-shaped array, as I understand that @grid[$x][$y] is supposed to be currently faster than @grid[$x;$y]

**Comment by bluebear94** [comment]
We're also using `@grid-indices` extensively; I wonder if that would pose a performance problem as well (as it has a separate entry for each cell). I wouldn't use it to initialize the cells in the grid constructor, at least.

Perhaps if we can generate the list lazily...

**Comment by ab5tract** [comment]
I'm not sure I see where that would pose a bottleneck, to be honest, but if you come up with an alternative approach that goes faster and only adds a reasonable amount of complexity, I will gladly merge.

**Comment by ab5tract** [comment]
Performance has dramatically improved since switching to `OO::Monitors`. I am closing this ticket. Please feel free to open a new one about any specific performance issues you would like to address.
