### ISSUE TITLE
Awesomize the clock example

### ISSUE THREAD

**Issue by japhb** [ab5tract/Terminal-Print#28]
Try to make the clock example as cool as possible.  Some ideas:

- Proper analog hands
- Large (and possibly animated) numbers drawn with pixels
- Multiple timezones at once
- Day/night/dawn/dusk animation
- Weather display
- Easter eggs at particular times or on particular dates
- (Ability to force any of the above to make it easy to show them off)

**Comment by japhb** [comment]
Stage 1: Get the baseline clock code back into shape

... is now complete on the master branch.  :-)

**Comment by ab5tract** [comment]
This is so cool.

**Comment by japhb** [comment]
Glad you like it.  :-)
