### ISSUE TITLE
Full width character MapViewer is glitchy

### ISSUE THREAD

**Issue by japhb** [ab5tract/Terminal-Print#34]
The full width character version of the rpg-ui MapViewer is glitchy, in that it will have rows print out with an extra space somewhere in the middle, or a character missing.  The net effect is both visually jarring and causes the MapViewer to "chew" into its right border.

Commit 6a50e9b in the fullwidth-mapviewer branch highlights this by extending the sleep between moves and making the background grid much more prominent.  You can see during individual frames that the rightmost areas of the background grid will have individual spans offset by one grid cell right or left, but that same area in the very next frame will be fine.  Over the course of the "finding the dragon" movement, the right border of the MapViewer will end up missing many chunks.

**Comment by japhb** [comment]
Commit 21f0702 has a bit more debugging output, and it appears that sometimes a grid.change-cell call doesn't actually "take" ... which is odd, to say the least.  I'm not entirely

**Comment by ab5tract** [comment]
It might be worth trying to leverage the 'conditions' in OO::Monitors to
see if adding a layer of "is-changing" and "is-ready" (or whatever) would
resolve the issue.

**Comment by japhb** [comment]
So after cutting down MapViewer.draw to bare bones, I discovered that it took two things to cause the glitches:

1. Create a Failure and then defang it (`Failure.new() // ''` will do it) in the inner map tile loop
2. Make T::P::Grid a monitor instead of a class.

Remove either of those, and the glitches went away.  Yes, when T::P::Grid is a class, it is *less* glitchy than when it's a monitor.

I'm exhausted now, but the next thing to do is try to golf this down into a test case.

**Comment by japhb** [comment]
I've golfed the client side code down to a [glitch-test example](https://github.com/ab5tract/Terminal-Print/blob/fullwidth-mapviewer/examples/glitch-test.p6).  Uncomment the `Failure.new()` line and run in a large terminal to see the `BUG` markers appear randomly.

**Comment by japhb** [comment]
I've now made the glitch-test example fully self-contained, not using any Terminal::Print code at all.  Time to report elsewhere ....

**Comment by japhb** [comment]
Reported to oo-monitors as https://github.com/jnthn/oo-monitors/issues/9 .

**Comment by japhb** [comment]
jnthn fixed this after an extended debugging session that required (among other things) adding a new op to MoarVM.  Quite the adventure.  :-)

**Comment by ab5tract** [comment]
@japhb, that's awesome! Was he able to nail the precomp bug as well?

**Comment by japhb** [comment]
He was not, but I was able to work around it.  Precomp works now.  :-)
