### ISSUE TITLE
Missing tput capabilities cause dying at compile time.

### ISSUE THREAD

**Issue by ramillies** [ab5tract/Terminal-Print#42]
The `Terminal::Print::Commands` just queries some tput capabilities for `{xterm,screen}{,-256color}` and `vt100` terminals. When the capabilties are missing, the module dies (it even fails to install because the tests die).

In my case it's quite unfortunate since my `vt100` doesn't have `smcup` and `rmcup`. Because of that the module fails to install (and I don't even use anything with `vt100` termcap...)

I'd just like to ask if someone has any useful idea about how to do the querying more "intelligently", because I don't. Of course I can (and will) download the source and hack it manually to do what I want, but it would be nice to be able to do it automatically.

**Comment by ab5tract** [comment]
This is really unfortunate. I didn't realize that `vt100` does not support screen saving/restore.

I think we could get around this by special casing when we find `vt100` in the `$TERM` env var and just stash a no-op in the lookup. Or instead of a no-op, we could alias it to `clear`, which does appear to be available.

No matter what we shouldn't be failing for a terminal class that you aren't even using.

Thanks for raising this!

**Comment by ramillies** [comment]
I think I found a neat way to at least make everything work if the missing capabilities are never required.

At compile time, if the `tput -T ... ` gives exit code 1, we don't let the program die. Instead, we
1) Put a "" or a clear sequence in the hash if the capability was smcup or rmcup.
2) Put a `fail "The capability $whatever is missing."` in the hash otherwise.

Now the `fail` generates a `Failure` which is sort of an unthrown exception. It throws only when you try to get its value. So as long as nobody wants the missing capability, the Failure is just there and the program can run OK. When the capability is queried, the Failure throws and the program dies.

How about that?

**Comment by ab5tract** [comment]
I do like it indeed! For #1, let's go with `clear`, as that will at least keep the library more or less the same in terms of usability on `vt100`.

The `Failure` approach is quite cool and feels quite idiomatic. Nice one.

**Comment by ramillies** [comment]
OK, I'll try to write it up. There are some theoretical gotchas to solve (like: if we say the exception and don't do the deinitialization, the poor user is left with a terminal all messed up. If we do the deinit, the exception will be cleared. :—).)

**Comment by ramillies** [comment]
Just to let you know, I hit no less than 2 core bugs on the way, so I'll've to rethink things a little bit :).

**Comment by ab5tract** [comment]
Do you consider this fixed by #43   or are we still in need of some bug fixes in core?

**Comment by ramillies** [comment]
Yes indeed, #43 is primarily a fix for this one.
