### ISSUE TITLE
Fail when constructing T

### ISSUE THREAD

**Issue by nkh** [ab5tract/Terminal-Print#44]
Hi, I get the below error message. 

I can run the examples in the distribution without problem, the only thing I see as different in in the context where the code is run is that the module that uses Terminal print is itself required.

perl6 script.pl -> call sub -> call sub2 -> require module_1 -> module_1 use Terminal::Print -> TP.new -> TP:Commads::Columns -> error

Let me know if I can help in any way.

Cannot invoke this object (REPR: Null; VMNull)
  in sub columns at /home/nadim/nadim/devel/repositories/perl_modules/P6-Data-Dump-Tree/lib/.precomp/144BF9F3B6429DD8176CC4E9795A0372370FB9A6.1502282226.01473/8D/8D9BB2D333E7A5BC4E6BB58A0891C315F3FAE42C line 1
  in method new at /home/nadim/nadim/devel/repositories/rakudo/install/share/perl6/site/sources/8718703D4E146A288FE08965B4DA555B8D5BD28E (Terminal::Print) line 83
  in block <unit> at /home/nadim/nadim/devel/repositories/rakudo/install/share/perl6/site/sources/8718703D4E146A288FE08965B4DA555B8D5BD28E (Terminal::Print) line 298
  in sub ddt_curses at /home/nadim/nadim/devel/repositories/perl_modules/P6-Data-Dump-Tree/lib/Data/Dump/Tree/Ddt.pm (Data::Dump::Tree::Ddt) line 9
  in sub ddt at /home/nadim/nadim/devel/repositories/perl_modules/P6-Data-Dump-Tree/lib/Data/Dump/Tree.pm (Data::Dump::Tree) line 105
  in block <unit> at ddt.pl line 6

**Comment by ab5tract** [comment]
I think over time I'm seeing more and more evidence that that T should not be exported by default.

Perhaps this syntax would be a decent fit:

```
  unit module Library;
  use Terminal::Print; # no auto-creation of Terminal::Print instance
```

and

```
  # my golfed screensaver script
  use Terminal::Print :T;
```

It would be cool if we can make it so that whatever named arg you use will become the exported constant in your script, a la:

```
  use Terminal::Print :term;
  term.initialize-screen;
```

There is a further implication in that we can't export any of our golf-y subs into the consuming namespace without first instantiating a `Terminal::Print` object. We can only export those commands for the non-library example.

But we can add them as methods onto `Terminal::Print` objects themselves so that library authors can be as concise as they please:

```
  my $t = Terminal::Print.new;
  $t.p($t.w/2, $t.h/2, 'golf stream');
```

**Comment by Xliff** [comment]
> It would be cool if we can make it so that whatever named arg you use will become the exported constant in your script, a la:
>   ```
>   use Terminal::Print :term;
>   term.initialize-screen;
>   ```

You _might_ be able to try something like this using a custom sub EXPORT, however I tried something like this and had problems with it. My attempts were trying to do something more advanced than yours, though. It _could_ be as simple as:

```perl
sub EXPORT($c) {
  {
    "\$$c" => Terminal::Print.new
  }
}
```

There may be a few issues with that syntax, but the general idea should be sound. Note that this would destroy the ability to use the normal export mechanism.

**Comment by ab5tract** [comment]
Yes, it seems like named arguments are going to be a problem here. I've had more problems with trying to do custom export packages than the sub form. We'll have to go with a regular string instead.

**Comment by Xliff** [comment]
Actually, I don't see a reason why named args wouldn't work in this situation. Just change the signature.

'''perl
sub EXPORT($c) # takes only single argument
```

just becomes:

```perl
sub EXPORT(*%c)
```

So the example can be rewritten as:

```perl
 sub EXPORT(*%c) {
  my %E = {};
  for %E.keys -> $s {
    %E{$s} = Terminal::Print.new;
  }
 
  %E; 
}
```

Hope that helps!

**Comment by nkh** [comment]
I believe it would be better to create T manually. Less surprise and also the possibility to scope it.

I was trying to replace the curses module and in that application I start and close curses multiple times, in between I do normal output on stdout.

**Comment by ab5tract** [comment]
@Xliff, named arguments without a corresponding EXPORT package seem to result in a compile time error:

```
Error while importing from 'TestExport': no such tag 'qoo'
```

This is using code that uses your proposed signature. I had thought the slurpy hash might make it work, as I had not tried that. But alas...

**Comment by Xliff** [comment]
@ab5tract: Looks like quotes it is.

**Comment by ab5tract** [comment]
@nkh , can you try using the branch 'no-more-auto-create'? If it fixes the issue for you I'll push it to master and bump the version.

**Comment by nkh** [comment]
@ab5tract, I get this error

===SORRY!===
Could not locate compile-time value for symbol TypeCheck::Argument

that's induced in the "use Terminal::Print ; "  I checked by removing it from the code,

**Comment by ab5tract** [comment]
This is quite strange. Do the examples work in the branch for you?

**Comment by nkh** [comment]
Yes, except clock that still uses T I believe.

remember that I do a require of a module that uses Terminal::Print, that may have an effect.

**Comment by ab5tract** [comment]
Hey @nkh, thanks for checking. I've patched the clock example in the branch.[^1]

Can I ask you to provide an example containing the broken code, perhaps a branch on p6-Data-Dump-Tree?

[1]: I'm pretty happy with this upgrade path:

```
  - use Terminal::Print;
  + use Terminal::Print <T>;
```

**Comment by nkh** [comment]
This branch fails
https://github.com/nkh/P6-Data-Dump-Tree/tree/terminal-print-fail

perl6 example/terminal_print_fail.pl should generate this error:

29 ~/4/P6-Data-Dump-Tree  +m2 [4b] L:terminal-print 6u p6 examples/terminal_print_fail.pl
Cannot invoke this object (REPR: Null; VMNull)
  in sub columns at /home/nadim/nadim/devel/repositories/rakudo/install/share/perl6/site/sources/8D9BB2D333E7A5BC4E6BB58A0891C315F3FAE42C (Terminal::Print::Commands) line 89
  in method new at /home/nadim/nadim/devel/repositories/rakudo/install/share/perl6/site/sources/8718703D4E146A288FE08965B4DA555B8D5BD28E (Terminal::Print) line 83
  in sub display_foldable at /home/nadim/nadim/devel/repositories/perl_modules/P6-Data-Dump-Tree/lib/Data/Dump/Tree/TerminalFoldable.pm (Data::Dump::Tree::TerminalFoldable) line 78
  in sub display_foldable at /home/nadim/nadim/devel/repositories/perl_modules/P6-Data-Dump-Tree/lib/Data/Dump/Tree/TerminalFoldable.pm (Data::Dump::Tree::TerminalFoldable) line 71
  in sub ddt_curses at /home/nadim/nadim/devel/repositories/perl_modules/P6-Data-Dump-Tree/lib/Data/Dump/Tree/Ddt.pm (Data::Dump::Tree::Ddt) line 9
  in sub ddt at /home/nadim/nadim/devel/repositories/perl_modules/P6-Data-Dump-Tree/lib/Data/Dump/Tree.pm (Data::Dump::Tree) line 105
  in block <unit> at examples/terminal_print_fail.pl line 5

**Comment by nkh** [comment]
Hi, was the example enough for you to find what's wrong ? Can I help in any other way?

**Comment by ab5tract** [comment]
Hey @nkh , sorry I haven't had a chance to dig too deep into it. I'll let you know if there's anything else I need from you. Hopefully I'll be able to find the bug and fix it over the weekend.

**Comment by nkh** [comment]
Great,

I want to get rid of NCurses and I also want to evaluate Terminal::Print for the next version of Asciio.

**Comment by ab5tract** [comment]
@nkh I'm still working on the fix for this. I'm hoping to nail it down this evening!

@japhb How do you feel about the change WRT the golf-subroutines / T ?

**Comment by ab5tract** [comment]
Ok I think I might have squashed it. Can you try with the latest version in the branch?

By the way, I've been testing via `zef --force-install install .` in the checked out branch of this repo and then running `perl6 -Ilib examples/terminal_print_fail.pl`.

@japhb, I'm inclined to merge this if it sorts out @nkh 's issue. Please raise any concerns now, if you have any!

**Comment by nkh** [comment]
hi,
 
There is no terminal_print_fail.pl in the directory but I  guessed you meant the one in my repo.

No crash, seems to work with the two line example I have. I will implement the curses replacement and test further. I need to find out how to handle keyboard and ^c handling as Curses does.

Thanks for the efforts.

If this works well I will do some speed tests to see if I can implement Asciio 2.0 with Terminal::Print, you're welcome to join the development if you  want to :)

**Comment by ab5tract** [comment]
Ah yes I did mean the script in your repo. 

I'm happy that you are giving `Terminal::Print` a shot at replacing `Curses`. That's really quite its use case. When I first saw DDT I thought that I would take a crack at coding in `Terminal::Print` support and maybe writing a blog post, but you've beat me to it.

The docs are a bit out of date but there's still some useful information in the Pod. This will be remedied for 1.0.0. @japhb is hard at work on getting input into shape: you can follow his progress on issue #19 .

In the meantime, if you have any questions or run into any issues, please don't hesitate to get in touch. Asciio 2.0

**Comment by nkh** [comment]
Good bye NCurses, hello T::P

https://i.imgur.com/zYKzNkC.png

**Comment by ab5tract** [comment]
Awesome!!
