### ISSUE TITLE
missing module in META6

### ISSUE THREAD

**Issue by nkh** [ab5tract/Terminal-Print#48]
Terminal::Print::DecodedInput

**Comment by ab5tract** [comment]
My apologies if this was somehow related to my earlier merge commit.

**Comment by nkh** [comment]
No problems, I am happy to help.

I send you a message earlier on irc #perl6; maybe we can find a moment to chat .

**Comment by ab5tract** [comment]
Hey Nadim,

Sure, hopefully this weekend I will have some time to login.
