### ISSUE TITLE
$*INITTIME is no longer a thing

### ISSUE THREAD

**Issue by AlexDaniel** [ab5tract/Terminal-Print#52]
https://github.com/ab5tract/Terminal-Print/blob/7d67e956c340c34105453af318a2e81d7800fb0b/examples/rpg-ui.p6#L1636
https://github.com/ab5tract/Terminal-Print/blob/7d67e956c340c34105453af318a2e81d7800fb0b/lib/Terminal/Print/Util/Timing.pm6#L44

See https://github.com/perl6/doc/commit/3b3c29b675a7bfc3aadd067c5d2f3f464932f0e0

**Comment by zoffixznet** [comment]
PR fixing this sent: https://github.com/ab5tract/Terminal-Print/pull/53
