### ISSUE TITLE
BoxDrawing signatures cause issues with method resolution

### ISSUE THREAD

**Issue by jjatria** [ab5tract/Terminal-Print#74]
I was experimenting with some widgets based on Terminal::Print, and had a class like

``` raku
class Box is Terminal::Print::Widget does Terminal::Print::BoxDrawing { ... }
```

This class worked fine when in a top-level script, but moving it to a separate file made it so that calling `Box.draw-box` would result in a `Cannot resolve caller draw-box...` error. I imagine this has to do with precompilation, but that is just a hunch.

I managed to track this down to the signatures used in some of the [BoxDrawing methods](https://github.com/ab5tract/Terminal-Print/blob/master/lib/Terminal/Print/BoxDrawing.pm6#L35), which look like

``` raku
multi method draw-hline($x1, $x2, $y, :$color!, :$style where %hline = $.default-box-style) { ... }
```

I think the problem is with those `:$style where %foo = $.default-box-style` constraints. Removing them (so that they were simply `:$style = $.default-box-style`) fixed the issue.

What is the purpose of those constraints? And should they be removed?

**Comment by japhb** [comment]
A `$bar where %foo` constraint is effectively checking `%foo.ACCEPTS($bar)`.  A hash is a subtype of `Map`, as you can see in the REPL:

```
> my %foo; say %foo.^mro;
((Hash) (Map) (Cool) (Any) (Mu))
```

[`Map.ACCEPTS`](https://docs.raku.org/routine/ACCEPTS#(Map)_method_ACCEPTS) for a `Cool` argument checks to see if the argument is a valid hash key.  Thus, effectively `:$style where %hline` is checking whether `%hline{$style}:exists`.

Can you post a short test example that I can use to investigate your issue?

**Comment by jjatria** [comment]
Sure. Thanks for looking into this!

[This commit](https://gitlab.com/jjatria/widget-experiments/-/commit/49ad3da7a45d14784a03496a03adf7dfb1622da3) broke the code in that repository, even though I _think_ all it does is move some class declarations to separate files.

Note that that code is actually using an unreleased version of Cache::LRU that [supports associative indexing](https://github.com/fayland/perl6-Cache-LRU/commit/b8b3f50985a7b17e758b048cf95bfbce81273dda), so it probably won't run out of the box.

I can get rid of the associative uses of Cache::LRU if it helps see the code running.

**Comment by japhb** [comment]
Hmmm, that is indeed weird.  OK, couple of questions:

1. If you put `no precompilation;` at the top of `lib/Rakui/Widget/Box.pm6`, does it suddenly start working again?
2. What is the output of `raku -v` for you?

**Comment by jjatria** [comment]
Yes, adding `no precompilation` at the top of that file fixes it

```
$ raku -v 
This is Rakudo version 2020.02.1 built on MoarVM version 2020.02.1
implementing Raku 6.d.
```

**Comment by jjatria** [comment]
Oh, it looks like something similar was filed a while ago: #66

**Comment by jjatria** [comment]
I've found that changing the hash declarations to constants fixes this issue with no user-facing changes. If the upstream issue is resolved, then this could be reverted. But until then, this can avoid users having to disable precompilation.
