### ISSUE TITLE
Missing \r when enabling module

### ISSUE THREAD

**Issue by coke** [ab5tract/Terminal-Print#83]
With this short script:

```
➜  trainer git:(main) ✗ cat foo.raku
use Terminal::Print::DecodedInput;

# Display character stream, exiting the program when 'q' is pressed
my $in-supply = decoded-input-supply;

say "hello";
my $result;
react {
    whenever $in-supply -> $c {
        $result = $c;
        done;
    }
}
say "there";
```
When I run it, and press a single character, I get this output:

```
➜  trainer git:(main) ✗ raku foo.raku
hello
     there
```

Where did the `\r` part of `\r\n` from the say go?

**Comment by japhb** [comment]
In short: When the terminal is put into raw mode, it stops doing certain translations automatically for you, and one of those is the \n -> \r\n translation.  That just means doing it yourself, or switching back and forth between raw and cooked modes.

(The above is slightly hand-wavey; the full answer includes things like "line discipline" and "kernel TTY driver" and such.  But unless you want to learn how to write things that reach back to the days of actual physical teletypes, the above is a reasonable summary.  :wink: )

**Comment by coke** [comment]
Ok. easy enough to manually print "\r" where needed here. If there's a way to switch between raw and cooked mode, that would be great to know as well.
